export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Ems } from "./Ems"
export { default as Franchise } from "./Franchise"
export { default as Contact } from "./Contact"
export { default as Faqs } from "./Faqs"